### ISSUE TITLE
2.0 Road Map

### ISSUE THREAD

**Issue by blainekasten** [blainekasten/shortcut.js#4]
To make managing this project simpler and safer I want to do a few things:
- [x] Change build process to webpack.
- [x] make dist UMD.
- [x] Use es6 transpiled code.
- [x] Seperate into modules that are compiled through webpack.
- [x] Use something like eslint to force some styleguides.
- [x] Create Good Test Coverage (drop jest, use karma)
- [x] Drop domLoaded code. Move selector usage responsible to user.

**Comment by blainekasten** [comment]
New API will be more along the lines of:

``` js
shortcut('mod a', document.querySelector('#input'))
```

**Comment by blainekasten** [comment]
What if we changed `bindsTo` to `then` and made it pseudo-Promisified. Any benefits to that? Better naming scheme. But confusion that it's not really a promise.

**Comment by blainekasten** [comment]
I'm going to say we should not do the `then`. it gets confusing when you want to remove a binding.. `unthen` doesn't make sense... So I think the 2.0 road map is done! I'm going to pre-release it now
